"""Facilitator-independent dry run of the 3-transaction join group.

Answers one question only: **does the AVM, and this contract, accept a group
shaped `[feePayer, axfer, appCall]` (or the `axfer_first` reordering) at all?**
It deliberately removes the facilitator from the path, so that a later
facilitator rejection can be attributed to facilitator policy rather than to a
malformed group or a contract bug.

To do that it submits *the exact bytes* `agents/build_join_group.py` produces.
The only substitution is the signature on the fee-payer leg: the facilitator
would normally countersign that leg, so here a locally-held throwaway account
(`DRYRUN_FEE_PAYER_KEY`) signs it instead. Everything else -- the group id, the
ABI arguments, the box reference, the buyer's two signatures -- is byte-identical
to what the real attempt sends.

The asset used is configurable via `DRYRUN_ASSET_ID` / `DRYRUN_APP_ID` so the run
does not depend on holding a captcha-gated public test asset; see
tests/FINDINGS.md for why that substitution was necessary and what it does and
does not prove.

Usage:
    python -m tests.dry_run_join_group --agreement-id 1 --variant fee_payer_first
"""

from __future__ import annotations

import argparse
import base64
import os

from algosdk import encoding, transaction
from dotenv import load_dotenv

from agents.build_join_group import (
    VARIANT_FEE_PAYER_FIRST,
    box_name,
    build_join_group,
)
from agents.common import AlgorandSigner, get_algod_client, get_buyer_signer

load_dotenv()


def sign_fee_payer_leg(raw_bytes: list[bytes]) -> list[transaction.SignedTransaction]:
    """Sign whichever leg `build_join_group` left unsigned.

    The builder returns raw msgpack: signed blobs for the buyer's legs, bare
    unsigned transaction bytes for the fee-payer leg. Decoding tells the two
    apart without having to know the variant's ordering.
    """
    # Already the base64 form algosdk's signer expects, as generated by
    # algosdk.account.generate_account().
    fee_payer_sk = os.environ["DRYRUN_FEE_PAYER_KEY"]

    signed: list[transaction.SignedTransaction] = []
    for raw in raw_bytes:
        obj = encoding.msgpack_decode(base64.b64encode(raw).decode())
        if isinstance(obj, transaction.SignedTransaction):
            signed.append(obj)
        else:
            signed.append(obj.sign(fee_payer_sk))
    return signed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--agreement-id", type=int, default=1)
    parser.add_argument("--variant", default=VARIANT_FEE_PAYER_FIRST)
    parser.add_argument("--amount", type=int, default=10000)
    args = parser.parse_args()

    app_id = int(os.environ["DRYRUN_APP_ID"])
    app_account = os.environ["DRYRUN_APP_ACCOUNT"]
    asset_id = int(os.environ["DRYRUN_ASSET_ID"])
    fee_payer_address = os.environ["DRYRUN_FEE_PAYER_ADDRESS"]

    algod_client = get_algod_client()
    buyer_signer: AlgorandSigner = get_buyer_signer()

    print(f"variant={args.variant} app_id={app_id} asset_id={asset_id}")
    print(f"buyer={buyer_signer.address}")
    print(f"fee_payer={fee_payer_address}")
    print(f"app_account={app_account}\n")

    group = build_join_group(
        algod_client=algod_client,
        buyer_signer=buyer_signer,
        fee_payer_address=fee_payer_address,
        app_id=app_id,
        app_account=app_account,
        asset_id=asset_id,
        amount=args.amount,
        agreement_id=args.agreement_id,
        variant=args.variant,
    )
    print(f"paymentIndex={group['paymentIndex']}")

    signed = sign_fee_payer_leg(group["rawBytes"])
    for i, stxn in enumerate(signed):
        txn = stxn.transaction
        print(f"  leg {i}: type={txn.type} sender={txn.sender} txid={txn.get_txid()}")
    print()

    print("--- simulate ---")
    sim = algod_client.simulate_raw_transactions(signed)
    group_result = sim["txn-groups"][0]
    failure = group_result.get("failure-message")
    if failure:
        print(f"simulate FAILED: {failure}")
        print(f"failed-at: {group_result.get('failed-at')}")
        return
    print("simulate OK (no failure-message)")
    for i, tr in enumerate(group_result["txn-results"]):
        logs = tr["txn-result"].get("logs") or []
        if logs:
            print(f"  leg {i} logs: {logs}")
    print()

    print("--- submit ---")
    txid = algod_client.send_transactions(signed)
    confirmed = transaction.wait_for_confirmation(algod_client, txid, 8)
    print(f"submitted, first txid={txid}")
    print(f"confirmed-round={confirmed['confirmed-round']}")
    print(f"group txids: {[s.transaction.get_txid() for s in signed]}")
    print()

    print("--- box state ---")
    name = box_name(args.agreement_id)
    box = algod_client.application_box_by_name(app_id, name)
    value = base64.b64decode(box["value"])
    print(f"box name (b64)={base64.b64encode(name).decode()}")
    print(f"box value (b64)={box['value']}")
    print(f"box value decoded as address={encoding.encode_address(value)}")


if __name__ == "__main__":
    main()
